### ISSUE TITLE
invalid json response body: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Tormidal** [mamoruuu/random-reddit#6]
Hi!

I've noticed this happens on occasion: if this is an issue with node-fetch, feel free to call me and idiot and close this issue. :)

They mostly all seem to have non-standard characters in the URL; however the webpages and JSON source pages themselves are still accessible.

```
FetchError: invalid json response body at https://www.reddit.com/r/wholesomehentai/comments/ntzp4r/mikuni_mizuki_the_country_virgin_fiancÃ©e/.json?utm_campaign=redirect&utm_medium=desktop&utm_source=reddit&utm_name=random_link reason: Unexpected token < in JSON at position 0
    at D:\Desktop\discord bot\node_modules\node-fetch\lib\index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.makeRequest (D:\Desktop\discord bot\node_modules\random-reddit\dist\utils.js:38:18)
    at async Object.getPost (D:\Desktop\discord bot\node_modules\random-reddit\dist\functions.js:12:22)
    at async getImage (D:\Desktop\discord bot\node_modules\random-reddit\dist\functions.js:27:16)
    at async getpic (D:\Desktop\discord bot\bot2.js:74:17)
    at async D:\Desktop\discord bot\bot2.js:241:15 {
  type: 'invalid-json'
}
```

```
FetchError: invalid json response body at https://www.reddit.com/r/Nekomimi/comments/o7l5f6/schwarz_é´éãã¤ã¿_arknights/.json?utm_campaign=redirect&utm_medium=desktop&utm_source=reddit&utm_name=random_link reason: Unexpected token < in JSON at position 0
    at D:\Desktop\discord bot\node_modules\node-fetch\lib\index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.makeRequest (D:\Desktop\discord bot\node_modules\random-reddit\dist\utils.js:38:18)
    at async Object.getPost (D:\Desktop\discord bot\node_modules\random-reddit\dist\functions.js:12:22)
    at async getImage (D:\Desktop\discord bot\node_modules\random-reddit\dist\functions.js:27:16)
    at async getpic (D:\Desktop\discord bot\bot2.js:74:17)
    at async D:\Desktop\discord bot\bot2.js:241:15 {
  type: 'invalid-json'
}
```

```
FetchError: invalid json response body at https://www.reddit.com/r/AzurLewd/comments/obfzll/Ã¤gir/.json?utm_campaign=redirect&utm_medium=desktop&utm_source=reddit&utm_name=random_link reason: Unexpected token < in JSON at position 0
    at D:\Desktop\discord bot\node_modules\node-fetch\lib\index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.makeRequest (D:\Desktop\discord bot\node_modules\random-reddit\dist\utils.js:38:18)
    at async Object.getPost (D:\Desktop\discord bot\node_modules\random-reddit\dist\functions.js:12:22)
    at async getImage (D:\Desktop\discord bot\node_modules\random-reddit\dist\functions.js:27:16)
    at async getpic (D:\Desktop\discord bot\bot2.js:81:17)
    at async D:\Desktop\discord bot\bot2.js:248:15 {
  type: 'invalid-json'
}
```

```
FetchError: invalid json response body at https://www.reddit.com/r/Nekomimi/comments/o6fqoz/beidou_ããµã­ããã¤_genshin_impact/.json?utm_campaign=redirect&utm_medium=desktop&utm_source=reddit&utm_name=random_link reason: Unexpected token < in JSON at position 0
    at D:\Desktop\discord bot\node_modules\node-fetch\lib\index.js:272:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.makeRequest (D:\Desktop\discord bot\node_modules\random-reddit\dist\utils.js:38:18)
    at async Object.getPost (D:\Desktop\discord bot\node_modules\random-reddit\dist\functions.js:12:22)
    at async getImage (D:\Desktop\discord bot\node_modules\random-reddit\dist\functions.js:27:16)
    at async getpic (D:\Desktop\discord bot\bot2.js:49:17)
    at async D:\Desktop\discord bot\bot2.js:168:15 {
  type: 'invalid-json'
}
```

**Comment by mamoruuu** [comment]
Hello!

It seems like you're trying to use the line `Nekomimi/comments/o6fqoz/beidou_ã��ã�µã�­ã��ã��ã�¤_genshin_impact/` as the `getImage` argument. You're supposed to put just `Nekomimi` (or `['AzurLewd', 'Nekomimi', 'wholesomehentai']`).

I clarify this moment in the README and jsdoc later

**Comment by AlexAtHome** [comment]
Hello!
Can you please send the code example that causes this errors?
Also, please, clarify, what do you use as an argument for `getImage`.

**Comment by Tormidal** [comment]
Of course!

the arguments are always in the form of the subreddit name(minus the r/; e.g. `ecchi` or `nekomimi`)

My nested calls looks like this:

```
async function getpic(fromSubreddit) {
	console.log(`received ${fromSubreddit}`);
	try {
		const image = await getImage(fromSubreddit);
		console.log(`retrieved pic at ${image}`);
		return image;
	} catch (error) {
		console.log(error);
		return error;
	}
}
```

```
let image = '';
		(async() => {
			image = await getpic(categories[command][0]);
				message.reply(image);
		})();
		console.log(`{LOG}User: ` + message.author.username + `, just used the ${command} command`);
		return;
```


It works flawlessly until it hits these posts - which all seem to have non-standard characters.

Here's an example of this faulty result vs. a normal/working results(warning potentially nsfw: https://i.gyazo.com/46c93eaf5c01c30be540cba938d44f76.png)

**Comment by AlexAtHome** [comment]
@Tormidal, can you check out the `2.0.2-2` version (from #5) and see if the problem still persists?

**Comment by Tormidal** [comment]
> @Tormidal, can you check out the `2.0.2-2` version (from #5) and see if the problem still persists?

Still persists on 2.0.2-2:

post was titled "Ägir in a Semi Bodysuit" but link shows as below "Ã¤gir_in_a_semi_bodysuit"

```
{ERROR}: caught error at FetchError: invalid json response body at https://www.reddit.com/r/AzurLewd/comments/ok4590/Ã¤gir_in_a_semi_bodysuit/.json?utm_campaign=redirect&utm_medium=desktop&utm_source=reddit&utm_name=random_link reason: Unexpected token < in JSON at position 0
```

**Comment by AlexAtHome** [comment]
Can't reproduce the bug in version 2.0.3. I consider it fixed since I don't use `random.json` approach anymore and I just pick a random post from a list, therefore there should not be any problems with parsing a HTML as a JSON.
